AWSTemplateFormatVersion: '2010-09-09'
Description: Vedantix ACM certificate in us-east-1

Parameters:
  DomainName:
    Type: String
    Default: vedantix.nl
  HostedZoneId:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub www.${DomainName}
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}-CertificateArn